### ISSUE TITLE
Implement loading on product screen

### ISSUE THREAD

**Issue by LucasRobs** [LucasRobs/ReactChallengeMercadoApp#2]
Users are without visual feedback on when products are being loaded.
Basically you must show a gif that visually represents the loading of products.
the choice of animation and implementation can be done as you prefer.

**Comment by LucasRobs** [comment]
Of course, all yours @joaovictor3g

**Comment by joaovictor3g** [comment]
but, i didnt understand the issue very much, is the loading for each product or the entire screen stay in loading while the products are brought from api?

**Comment by LucasRobs** [comment]
tanks
